- name: Create pods using deployment 
  hosts: kubernetes 
  
  tasks: 
  - name: delete the previous deployment
    command: git clone https://github.com/jch941022/gitops-repository.git

  - name: create a deployment
    command: kubectl apply -f gitops-repository/service/eks-manifest/application.yaml